### ISSUE TITLE
Game Crashes on startup

### ISSUE THREAD

**Issue by supermario9590** [DeadlyMC/QuickCarpet#89]
I am trying to run this mod on 1.16.5 on MultiMC, the only other mod I have installed is MaLiLib which is a dependency and the game crashed whenever I try to start it. This is the log:

```[14:51:02] [main/FATAL]: Unreported exception thrown!
java.lang.ExceptionInInitializerError: null
	at quickcarpet.QuickCarpetClient.<init>(QuickCarpetClient.java:23) ~[quickcarpet-3.0.0.jar:?]
	at quickcarpet.QuickCarpetClient.<clinit>(QuickCarpetClient.java:19) ~[quickcarpet-3.0.0.jar:?]
	at net.minecraft.class_317.redirect$zfo000$adjustTickSpeed(class_317.java:522) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_317.method_1658(class_317.java:16) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1012) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:681) [intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:215) [intermediary-minecraft-1.16.5-client.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226) [fabric-loader-0.11.3.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146) [fabric-loader-0.11.3.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.3.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.util.ConcurrentModificationException
	at java.util.TreeMap.callMappingFunctionWithCheck(TreeMap.java:742) ~[?:?]
	at java.util.TreeMap.computeIfAbsent(TreeMap.java:558) ~[?:?]
	at quickcarpet.pubsub.PubSubManager.getOrCreateNode(PubSubManager.java:42) ~[quickcarpet-3.0.0.jar:?]
	at quickcarpet.pubsub.PubSubInfoProvider.<init>(PubSubInfoProvider.java:18) ~[quickcarpet-3.0.0.jar:?]
	at quickcarpet.helper.TickSpeed.<clinit>(TickSpeed.java:38) ~[quickcarpet-3.0.0.jar:?]
	... 22 more
---- Minecraft Crash Report ----
// You're mean.

Time: 03/06/2021, 14:51
Description: Unexpected error

java.lang.ExceptionInInitializerError
	at quickcarpet.QuickCarpetClient.<init>(QuickCarpetClient.java:23)
	at quickcarpet.QuickCarpetClient.<clinit>(QuickCarpetClient.java:19)
	at net.minecraft.class_317.redirect$zfo000$adjustTickSpeed(class_317.java:522)
	at net.minecraft.class_317.method_1658(class_317.java:16)
	at net.minecraft.class_310.method_1523(class_310.java:1012)
	at net.minecraft.class_310.method_1514(class_310.java:681)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.util.ConcurrentModificationException
	at java.base/java.util.TreeMap.callMappingFunctionWithCheck(TreeMap.java:742)
	at java.base/java.util.TreeMap.computeIfAbsent(TreeMap.java:558)
	at quickcarpet.pubsub.PubSubManager.getOrCreateNode(PubSubManager.java:42)
	at quickcarpet.pubsub.PubSubInfoProvider.<init>(PubSubInfoProvider.java:18)
	at quickcarpet.helper.TickSpeed.<clinit>(TickSpeed.java:38)
	... 22 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.1, AdoptOpenJDK
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), AdoptOpenJDK
	Memory: 269110160 bytes (256 MB) / 1072693248 bytes (1023 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 8
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx2048m
	Launched Version: MultiMC5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 1050 Ti with Max-Q Design/PCIe/SSE2 GL version 4.6.0 NVIDIA 462.30, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: fabric/quickcarpet-api, fabric/fabric-resource-loader-v0, fabric/fabricloader
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
#@!@# Game crashed! Crash report saved to: #@!@# C:\Users\anish\Documents\MultiMC\instances\QuickCarpet\.minecraft\crash-reports\crash-2021-06-03_14.51.03-client.txt
Process exited with code -1.```

I do not know what is causing this but I want to try this mod so any help would be appreciated

**Comment by skyrising** [comment]
Fixed in fa35eba6, use version 3.1.0+
